### ISSUE TITLE
Footer icons not vertically centered

### ISSUE THREAD

**Issue by a-qxin** [park-junha/where-to#96]
Recommendations:
- [ ] Remove selection border
- [x] Remove top spacing (thank you @eyoa!)

Screenshot:
![Screen Shot 2021-07-20 at 11 24 39 PM](https://user-images.githubusercontent.com/5442091/126442014-5b8de6ff-9b9f-4491-934c-083e86ac72b2.png)

**Comment by a-qxin** [comment]
Seen on below version of Google Chrome
![Screen Shot 2021-07-20 at 11 32 00 PM](https://user-images.githubusercontent.com/5442091/126442192-3df3cec8-041a-4ef9-968d-1b88bdc5de6f.png)

**Comment by eyoa** [comment]
Hi, 
Is this issue still open? If so I'd like to give it a go.

**Comment by eyoa** [comment]
The icon image itself isn't square so it wasn't vertically centered.
I adjusted the top padding value in the scss file for the footer button to be 2px.

**Comment by park-junha** [comment]
> The icon image itself isn't square so it wasn't vertically centered.
> I adjusted the top padding value in the scss file for the footer button to be 2px.

Thank you so much for contributing! I'll look at your PR soon.

**Comment by park-junha** [comment]
Will open separate issue for selection border
